services:
  funcionalhealthtechchallenge:
    image: funcionalhealthtechchallenge:latest 
    build:
      context: ./FuncionalHealthTechChallenge
      dockerfile: Dockerfile
    container_name: funcional_api
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ConnectionStrings__DefaultConnection=Server=db;Database=FuncionalHealthDemo;User Id=sa;Password=1q2w3e4r@#$;TrustServerCertificate=True
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "5000:8080"
    restart: always

  db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: Funcionalsqlserver
    environment:
      SA_PASSWORD: "1q2w3e4r@#$"
      ACCEPT_EULA: "Y"
    ports:
      - "1433:1433"
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P '1q2w3e4r@#$' -C -Q 'SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 10